sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
      - master
notifications:
  email: false
node_js:
  - 7.10
before_install:
  - npm i -g yarn
test:
  - yarn test
install: yarn install